package com.uniruta.app.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF1B5E9B)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BlueContainerLight = Color(0xFFD3E4FF)
val BlueOnContainerLight = Color(0xFF001C39)
val AmberSecondaryLight = Color(0xFF8C5000)
val AmberOnSecondaryLight = Color(0xFFFFFFFF)
val AmberContainerLight = Color(0xFFFFDDB7)
val AmberOnContainerLight = Color(0xFF2C1700)
val SurfaceLight = Color(0xFFFCFCFF)
val OnSurfaceLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFDFE2EB)
val OnSurfaceVariantLight = Color(0xFF43474E)
val OutlineLight = Color(0xFF73777F)

val BluePrimaryDark = Color(0xFFA3C9FF)
val BlueOnPrimaryDark = Color(0xFF00325B)
val BlueContainerDark = Color(0xFF004880)
val BlueOnContainerDark = Color(0xFFD3E4FF)
val AmberSecondaryDark = Color(0xFFFFB868)
val AmberOnSecondaryDark = Color(0xFF4A2800)
val AmberContainerDark = Color(0xFF6A3C00)
val AmberOnContainerDark = Color(0xFFFFDDB7)
val SurfaceDark = Color(0xFF1A1C1E)
val OnSurfaceDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF43474E)
val OnSurfaceVariantDark = Color(0xFFC3C7CF)
val OutlineDark = Color(0xFF8D9199)
